export default[
    {
        user: 'doa1',
        subject:  'Doa Pengajian',
        isi:'الْحَمْدُ للهِّۢ الَّذِيْ أنْعَمَ عَلَينْاَ بِنِعْمَةِ الإِيمَانِ وَالإِسْلاَمِ وَهِيَ أعْظمَ النِّعَمِ، أشْهَدُ أْنْ لآ إلِۢهَ إلِاَّ اللهُّۢ الراَّفِعُ الْحَكَمُ، وَأشْهَدُ أنَّ مُحَمَّدًا عَبدْهُ وَرسُوْلُهُ أشْرفُ الأنَامِ، صَلَوَاتُ اللهِّۢ وَسَلاَمُهُ وَبرَكَاتُهُ عَلَيْه وَعَلٓى الِۢ ِه وَصَحْبِه الْكِراَمِ، أمَّاَ بَعْدبِسْمِ اللهِّۢ الرحَّمۢنِ الرحِّيمِ، الْحَمْدُ للهِۢ ر ِّبَ الْعَالمَيْنَ، الَلّۢهُمَّ صَل صَلاَةً كا ِمَلَةً وَسَ ِّلِمْ سَلامًا تَامًّا عَلۢىِ سَ ِّي ِدنَا مُحَمَّ ٍد الَّ ِذِيْ تنَحَلُّ بِه الْعُقَدُ وَتنَفْرِجُ بِه الْكُربَ وَتقْضۢى بِه الْحَوَآ ِئجُ وَتنُاَلُ بِه الرغَّآ ِئبُ وَحُسْنُ الْخَوَاتِمِ وَيُسْتسَقَى الْغَمَامُ بِوَجْهِه الْكَرِيمِ وَعَلٓى آلِه وَصَحْبِه فِيْ كُ ِّل لمَحْة وَنفََسٍ بِعَدَدِ كُِّ ل مَعْلُومٍ لَكَ، رَبنَّاَ هَبْ لَناَ مِنْ أزَْوَاجِناَ وَذ ِّرُيَّاتِناَ قُرةََّ أعَْيُنٍ وَاجْعَلْناَ للِْمُتقَِّينَ إمَِامًا، رَبنَّاَ آتِناَ فِي الدُّنيَْا حَسَنةًَ وَفِي الآْخِرَةِ حَسَنةًَ وَقِناَ عَذَابَ الناَّرِ وَالْحَمْدُ للهِِّۢ ر ِّبَ الْعَالمَيِْنَ',
        latin:'Alhamdu lIllaahil la-dzii an ‘ama ‘alainaa bi ni’matil iimaani wal islaami wa hiya a’zhamun  ni’am. Asy-hadu anna muhammadan ‘abduhu wa rasuluhu asy-raful anaam. Shalawaatullahi wa salamuhu wa barakatuhu ‘alaihi wa ‘alaa aalihi wa shahbihil kiraam, ammaa ba’du.Bismillahirrahmanirrahim. Alhamdulillahi rabbil ‘aalamiin. Allaahumma shalli shalaatan(g) kaamilataw wa sallim saalaaman taamman ‘alaa sayyidinaa muhammadinil la-dzii tanhallu bihil ‘uqadu wa tanfariju bihil kurabu wa tuq-dhaa bihil hawaa-iju wa tunaalu bihir ra-ghaa-ibu wa husnul khawaatimi wa yustasqal ghamaamu bi wajhihil kariimi wa ‘alaa aalihi wa shahbihi fii kulli lamhatiw wa naafasim bi’adadi kulli ma’luumil lak(a). Rabbanaa hab lanaa min azwaajinaa wa dzurriyyaatina qurrata a’yuniw waj’alnaa lilmuttaqiina imaamaa. Rabbanaa aatinaa fid dun-yaa hasanah wa qinaa ‘a-dzaaban naar. Walhamdulillahi rabbil ‘aalamiin.',
        arti:'“Segala puji bagi Allah yang telah memberikan nikmat kepada kita dengan nikmat iman dan Islam, dan itulah seutama-utama nikmat. Aku bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Meninggikan lagi Yang Maha Menetapkan Hukum. Dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya yang merupakan seutama-utama manusia. Rahmat, salam dan berkah Allah semoga tetap tercurah keharibaan beliau SAW, keluarga serta para sahabatnya yang mulia. Adapun sesudah itu”.“Dengan nama Allah yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah Tuhan semesta alam. Ya Allah, curahkanlah rahmat dan keselamatan yang sempurna kepada junjungan kami yaitu Nabi Muhammad, semoga terurai dengan berkahnya semua buhulan, dilepaskan dari segala macam kesusahan, ditunaikan segala macam kebutuhan, tercapai segala macam keinginan dan memperoleh husnul khatimah (akhir yang baik), dicurahkan air hujan rahmat disebabkan berkah pribadinya yang mulia. Juga rahmat dan keselamatan tersebut dicurahkan kepada keluarga dan para sahabatnya disetiap kedipan mata dan hembusan nafas, bahkan sebanyak pengetahuan Engkau. Wahai Tuhan kami, anugerahkanlah kepada kami dari istri - istri kami dan keturunan kami suatu pemandangan yang menyejukkan mata, dan jadikanlah kami sebagai pemimpin orang – orang yang bertaqwa. Wahai Tuhan kami, berilah kami kebaikan di dunia dan di akhirat, dan peliharalah kami dari siksa neraka. Segala puji bagi Allah Tuhan semesta alam”.',
        
        
    },
    {
        user: 'doa2',
        subject:  '',
        isi:'',
        latin:'',
        arti:'',
        
    },
    {
        user: 'doa3',
        name: 'duduk',
        subject: 'doa duduk'
        
    },
    {
        user: 'doa4',
        name: 'berdiri',
        subject: 'doa berdiri'
    },
    {
        user: 'doa19',
        subject: 'doa amar ma ruf nahi mun kar,isra mi raj,dll',
        isi:'  الْحَمْدُ لِلهِ خَالِقِ الأْنَامِ وَحَاكِمِ الْحُكَّامِ وَعَاجِلِ النوُّر وَالظَّلامِ اشَهَدُ انَ لاۤ اِلٰهَ اِلاَّ اللهُ ذُو الْجَلاَلِ وَالإِكْراَمِ السَّلامَ، وَأشْهَدُ أَّنَّ مُحَمَّدًا رسُوْلُ اللهِّۢ المْبَعُوْثُ بِشَراَئِعِ الإِسْلامِ الَلّۢهُمَّ صَ ِّل عَلۢى خَيرْ الأْنَامِ، وَعَلٓۢى الِۢه وَأصَحَابِه الْكِراَمِ ، وَعَلَيْناَ مَعَهُمْ إلِۢى يوَمِ الْقِيَامَة أمَا بَعْدُ أعَوْذُ بِاللهِّۢ مِنَ الشَّيْطَانِ الرَّيمْ، بِسْمِ اللهِ الرحْمَنِ ال ِّرحِيمِ الْحَمْدُ للِهِ ر ِّبَ الْعَالمَيْنَ، الَلّۢهُمَّ صَ ِّل عَلۢى مُحَمَّدٍ ، صَلاَةً مُوْصِلَةً اِلَيْه جَامِعَةً عَلَيْه يتَلُوْهاَ الِّ لسَانِ وَيتَ ِصَّلُ بِ ِعلْ ِمهَا الجَناَنِ وَتَنبْ ِعَثُ أسَراَرهَاِفى الارَكَانِ فتَجَمَعُ القَلْبَ عَلىَ شُهُوْدِهِ وَالسَرَّ عَلَى نفُوُدِهِ وَالجَوَارحَ عَلۢى تَحَمُّلِ ادَٓاءِمَا تُحُ ِّملَتْ وَال ِّصدْقَ فِيْ مُعَامَلة مَنْ عَامَلَتْ وَعَلىۢٓ الِۢه الكِراَمِ وَاصَحَابِه الاْعْلامِ الَلهُمَّ ن ِّوَرْ قُلُوْبنَاَ وَاشْرحْ صُدُوْرنَا بِرحْمَ ِتكَ يۢٓاارَحَمَ الرَّا ِح ِميْنَ، اللّۢهُمَّ إِنَّا نَعُوْذُ بِكَ أنَ تزَلَّ أقْدَامَناَ عَلۢى ال ِّصراَ ِطِفيْ الناَّرِ يوَمَ تزَلَّ أقْدَامُ المنُاَ ِف ِقيْنَ وَالمْشُر ِكِيْنَ، رَبنَّاَ نَ ِّجناِمنَ الْقَوْمِ الظَّ ِالمِيْنَ، اللّۢهُمَّ نَعْت ِذَرُ إلَيْكَ ممَّا صَنعَ هٓؤُۢلا ِءٓۢ وَتبَرْئُ إلَيْكَ ممَّا صَنعَ هءُٓۢلا ِءۢٓ، رَبنَّآَ اتِۢناَ في الدُّنيْا حَسَنةً وَفِي الاْۢخِرةَ حَسَنةً وَقِناَ عَذَابَ الناَّرِ، يَا عَزِيْزُ يَا غَفَّارُ إنَّكَ عَلۢى كُ ِّل شَيءْ قَدِيْرٌ  وَالْحَمْدُ للهِ ر ِّبَ الْعالمَيِنَ ',
        latin:'Alhamdu lilaahil la-dzi la syarala fid dun-yaa wal aakhirati illaa syarata haa atih, asy-hadu al laa laaha ilallasho wahdahu laR syarika lah, was asy hadu anna muhammadan abduhu wa rasulauh. Allahumma shali alaa sayyidinaa muhammadiw wa alaa aalihi wa ash -haabih, ammaa ba du , A uu-dzu billaahi minasy syai thaanir rajim Bismillaahir rahmaanir rahim Alhamdu tillaahi rabbil aalamin Allaahumma shalli wa sallim alaa muu shilatan ilaihi jaami or alaihi yatluuhai lisaanu wa yatta shilu bi imihal janaanu wa tamba tsu asraaruhaa fil arkaani ta tajma ul galba alaa syuhuudihi was sirra alaa nufuu-dzihi wat jawaariha alaa tahammuli adaa-i maa tuhummilat wash shidga fi mu aamaiati man aamalat wa alaa aalihil kiraami wa ash haabihil a laam Allaahumma nawwir qulubanaa wasy rah shuduuranaa bi rahmatika yaa arhamar raahimiin Allaahumma innaa na uu-dzu bika an tazilla aqdaamanaa alash shiraathi fin naari yauma tazilla aqdaamul munaafiquna wal musy rikiin Rabbanaa najjinaa minal qaumizh zhaalimin Allaahumma na ta dziru ilaika mimmaa shana a haa-ulaa-iwa rabra u ilaika mimmaa shana a haa-uulaa-i Rabbanaa aatina fid dun yaa hasanah, wa fil aa khirati hasanah, wa qinaa a dzaaban naar yaa azizu yaa ghaffaar innaka alaa kulli syai ing qadir Walhamdu lillaahi rabbil aalamin',
        arti:'Artinya:" Segala puji bagi Allah yang tiada kemaliaan di dunia dan di akhirat selain kemuliaan untuk taat kepada-Nya. Aka bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Esi. tiada sekutu bagi-Nya. Dan aku bersaksi bahwa Nabi Muhammad adalah hamba dan utusan-Nya. Ya curahkanlah rahmat kepada Nabi Muhammad, keluarga dan para sahabatnya. Adapun sesudah itu , Aku berlindung kepada Allsh daxi segala godaan syetan yang terkurtok Dengan nama Allah yang Maha Pengasih lagi Maha Penyayang Segala puji bag: Allah Tuhan semesta Alam Ya Allab, corahkanlah rahmat dan salam kepada junjungan kami yaitu Nabi Muhammad, rahmat yang sampai kepadanya, kumpul di atas, yang mana lisan membacanya vang menimbulkan rabasia rahasianya di dalam semua rukun lalu dapat mengumpulkan hari manusia atas pensalksiannya dan rahasia atas kelangsungannya dan anggota-anggota hadan atas tanggungan sampa ada yang ditanggung, dan kejujuran di dalam perbuatan orang yang berbuat.Shalawat dan salam semoga tercurah pula kepada keluarga beliau yang mulia dan para sahabatnya yang besar Ya Allah, berikanlah cahaya untuk hati kamı, dan lapangkanlah dada kansi discbablan memperoleh rahmat Ma wahai Tuhan yang paling penyayang Ya Allah, sesungguhnya kami berlindung kepada- Mu dari tergelincirnya kakikami di atas jalan di neraka pada harı ketika kaki kaku orang munafik dan orang-orang musynk tergelinair Wahai Tuhan kami, selamatkanlah kami dan orang orang yang zalim Ya Allah, sesungguhnya kami memobon kepada-Mu keselamatan dan perbuatan mereka dan kami memohon dijauhkan dari perbuatan mereka.Wahai Tuhan kami berilah kami kebaikan di dunia, dan kebaikan diakhirat dan peliharalah kami darı siksa neraka, wahai Tuhan yang Maha Perkasa lagi Maha Pengampun, sesungguhnya Engkau Maha Kuasa atas segala sesuaru Segala puji bagi Allah Tuhan semesta alam".',
    },
    {
        user: 'doa20',
        subject: 'doa acara kajian rutin,ulang tahun,dll',
        isi:'الْحَمْدُ لِلهِ الَّذِيْ لاَ شَرفَ فِيْ الدُّنيْا وَالاۢخِرةَ إلِاَّ شَرفَ طاَعَتِهِ، أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ وَحْدَهُ لاَ شَرِيْكَ لَهُ، وَأشَهَدُ أنَ مُحَمَّدًا عَبدُهُ وَرسُوْلُهُ، الَلّۢهُمَّ صَ ِّل عَلۢى سَ ِّيدِنَا مُحَمَّدٍ، وَعَلۢٓى الِۢه وَأصَحَابِه الْكِراَمِ، وَعَلَينْاَ مَعَهُمْ إلِۢى يوَمِ الْ ِقيَامَة، أمَا بَعْد بِسْمِ اللهِ الرحَّمَنِ الِّرحِيمِ. حَمْدَ الشَّاكِرِيْنَ حَمْدَ الناَّعِمِيْنَ حَمْدًا حَمْدًا وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ، الَلَّهُمَّ صَ ِّل وَسَ ِّلمْ وَبَاركْ عَلۢى سَ ِّيدِنَا مُحَمَّدٍ وَعَلٓى الِۢ سَ ِّي ِدنَا مُحَمَّ ٍد، صَلاَةً وَسَلامَةً وَبرَكَةً دَٓا ِئمَةً مُسْت ِمَرةً تَدُوْمُ بِدَوَ ِامكَ وَتبَقْۢى بِبقَآ ِئكَ وَتَخْلُدُ بِخُلُوْ ِدكَ ولَاَ غَايَةَ لَهَا دُوْنَ مَرضَاتِكَ ولَاۢ جَزَاءَ لِقَائِلهَا وَمُضَ ِّليْهَا غَيرْ جَنتَّكَ وَالنظَّرَ إلِۢى وَجْهِكَ الْكَرِيمِ، الَلّۢهُمَّ اغْفِرْ لَناَ خَطِيئْتَنَاَ وَجَهْلَناَ وَإسْراَفنَاَ فِيْ أمُوْرنَا وَمَٓا أنَتْ أعَلَمُ بِه مِناَّ، الَلّۢهُمَّ رَبنَّاَ اغْفِرْ لَناَ وَلوَالدَينْاَ وَارحَمْهُمَا كَمَا رَبيَانَا صِغَاراً، الَلّۢهُمَّ إنَّا ضَعِيْفٌ فقَ ِّونَا وَإنَّا ذلَيْلٌ فَأعِزَّنَا وَإنَّا فقَيرْ فَأغْنِناَ يٓۢا أرَحَمَ الراَّحِمِيْنَ، الَلّۢهُمَّ أرَنَا الْحَقَّ حَقًّا وَارْزُقْناَ اتِّباَعَهُ وَأرَنَا الْباَ ِطلَ بَا ِطلاً وَارْزقْناَ اجْ ِتناَبَهُ، الَلَّهُمَّ إنَّا نَعُوذُ بِكَ مِنْ جَهْدِ البلَاءَ، وَدَركَ الشَّقَاءِ، وَسُوءِ القَضَاءِ، وَشَمَاتَة الأعَدَاءِ، رَبنَّآَ اتِۢناَ فِي الدُّنْيَا حَسَنةً وَفِي الاْۢخِرةَ حَسَنةً وَقِناَ عَذَابَ الناَّرِ، وَالْحَمْدُ للهِّۢ ر ِّبَ الْعَالمَيْنَ',
        latin:'Alhamdu lilaahil la-dzi laa syarafa fid dun-yaa wal aakhirati illaa syarafa haa atih, asy-hadu al laa ilaaha ilallaahu wahdahu laa syarika lah, was asy hadu anna muhammadan abduhu wa rasulauh. Allahumma shali alaa sayyidinaa muhammadiw wa alaa aalihi wa ash -haabih, ammaa ba du Bismillaahir rahmaanir rahiim Hamdasy syaakirin hamdan naa imiin, hamday yuwaatii ni amahu wa yukaafi mazidah, rabbanaa lakal hamdu kamaa yamba ghi t jalaali wajhikal kariimi wa a zhiumi sulthaanika Allaahumma shalli wa sallim wa baarik alaasayyidinaa muhammad wa alaa aali sayyidinaa muhammad shalaatan wa salaamatan wa barakatan daa imatan mustamirratan taduumu bidawaamika wa tabqaa bi baqaa ika wa takh ludu bi khuluudika wa laa ghaayata lahaa duuna mar dhaatika wa laa azaa a li qaa ilihaa wa mu shallihaa ghaira jannatika wan na zhan ilaa wajhikal karim Allaahummaghtir lanaa kha thiatanaa wa jahlanaa wa israatanaa fi umuurinaa wa maa anta a lamu bihi minnaa Allaahummaghtirlanaa wa waalidiinaa warhamhum kamaa rabba yaanaa shi ghaaraa Allaahumma innaa dha ifun fa gawwinaa wa innaa dzalilun fa a izzanaa wa innaa taqiirun fa agh ninaa yaa arhamar raahimin Allaahumma arinal haqga haqqan warzuqnat tibaa ah wa arinal baa thila baa thiian warzuqnajtinaabah Allaahumma innaa na uu dzu bika min jahdil bataa iwa darkisy syaqaa i wa suu il qa dhaa i wa syamaatatil a daa Rabbanaa aatinaa fid dun yaa hasanah wa fil aakhirati hasanah, wa qinaa a dzaaban naar Walhmadu lillahi tan aalamin',
        arti:'Artinya : "Segala puji bagi Allah yang tiada kemaliaan di dunia dan di akhirat selain kemuliaan untuk taat kepada-Nya. Aka bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Esi. tiada sekutu bagi-Nya. Dan aku bersaksi bahwa Nabi Muhammad adalah hamba dan utusan-Nya. Ya curahkanlah rahmat kepada Nabi Muhammad, keluarga dan para sahabatnya. Adapun sesudah itu rabbi Dengan nama Allah yang Maha Pengasih lagi Maha 1 penyayang Sebagimana orang orang yang bersyukur. dan orang yang memperoleh nikmar sama memuj, dengan yang sebanding dengan nikmat-nikmat Nya dan menjamin tambahnya Wahai Tuhan kami, bagi Mu segala pui sebagaimana apa yang patut bagi keluhuran Zat Mu mulia dan keagungan kekuasaan-Mu Ya Allah. curahkanlah rahmat, salam dan keberkahan kepada junjungan kamı yaitu Nabi Muhammad beserta keluarganya rahmat, salam dan berkah yang terus-menerus, a kekal karena kekekalan-Mu ia abadi karena keabadian Mu, ta langgeng karena kelanggengan-Mu, tiada ujung baginya tanpa keridhaan-Mu dan tiada balasaan bagı pembacanya dan yang memintakan rahmat selain surga-Mu dan memandang wajah-Mu yang Mulia Ya Allah, ampunilah kami, kesalahan-kesalahan kami. kebodohan kami, segala sesuatu yang menjadi urasan kami yang melampau batas serta segala apa yang mana Engkau lebıh mengetahui lebih banyak tentang kami. Ya Allah, ampunilah kami dan kedua orang tua kami, rahmatilah mereka telah mendidik kami di waktu kecil. Ya Allah, sesungguhnya kami adalah lemah, maka kuatkanlah kami, nyata kami hina, maka muliakanlah kami, dan nyata kami fakir (miskin), maka kayakanlah kami wahai Tuhan yang paling penyayang. Ya Allah, tunjukkanlah kepada kami yang benar itu benar, dan berilah kami Karena sesungguhnya tidak ada yang dapat menjauhkannya selain Engkau. Ya Allah, jadikanlah kami orang yang bersyukur, jadikanlah kami orang yang sabar, dan kami adalah orang-orang yang kecil dalam pandangan mata kami dan besar dalam pandangan manusia. Tuhan kami, berilah kami baik di dunia dan kebaikandi akhirat, dan peliharalah kami dari siksa neraka Maha suci Tuhanmu, Tuhan yan Maha Perkasa terhadap apa yang mereka sifatkan Keselamatan semoga tercurah kepada rasul-rasul, dan segala puji bagi Allah Tuhan semesta alam. ".',
    },
    {
        user: 'doa21',
        subject: 'doa acara silaturahmi,dll',
        isi: 'الْحَمْدُ لِلهِ الْعَزِيزْ الْغَفَّارِ الْحَليِمِ السَّتاَّرِ، أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ الْوَاحِدُ الْجَباَّرُ، وَأشْهَدُ أنَّ سَ ِّيدَنَا وَحَبِيبْنَاَ مُحَمَّدًا رسُوْلُ اللهِّۢ عَلَّمَناَ الاِحْتِيَاطَ لِننَجْوِمنَ الاَخْطَارِ، فَصَلَوَاتُ اللهِّۢ وَسَلامُهُ عَلَيْه وَالِۢه وَصَحْبِه الاَخْيَارِ، أمَّا بَعْدُ بسْمِ اللهِ الرَّحْمَنِ ال ِّرحِيمِ. الْحَمْدُ للهِ ر ِّبَ الْعَالمَيْنَ الَلَّهُمَّ صَ ِّل وَسَ ِّلمْ وَبَاركْ عَلۢى سَي ِّ ِدنَا مُحَمَّ ٍد الْفَا ِتحِ لماَ أغْلِ-قَ وَالْخَا ِتمِ لماَ سَبقَ وَالِناَّصرِ الْحِ ِّق بِالْح ِّق وَالِهَا ِديٓ إلِۢى صراَ ِطكَ المْسْت ِقَيمْ، صَلّۢى اللهُّۢ عَلَيْه وَعَلٓى الِۢه وَأصْحَابِه حَقَّ قَدْرهِ وَمِقْدَارهِ الْعَظِيمْ، الَلّۢهُمَّ إنِّا نَعُوْذُ بِكَ مِنَ الْهَ ِّم وَالْحَزَنِ وَنَعُوْذُ بِكِ منَ الْعَجْزِ وَالْكَسَلِ وَأعُوذُ بِكَ منَ الْجُبْنِ وَالْبخُلِ وَأعُوذُ بِكَ مِنْ غَلَبةَ الدَّيْنِ، وَقَهْرِ ال ِّرجَالِ، الَلَّهُمَّ اكْفِناَ بِحَلالِكَ عَنْ حَراَمِكَ وَأغَنِناَ بِفَضْلكِ عَمَّنْ سِوَاكَ، الَلّۢهُمَّ اغْفِرْ لَناَ ذنُوْبنَاَ وَاذْهِبْ غَيظْ قُلُوْبِناَ وَاجِرنْا مِنَ الشّيْطَانِ، رَبنَّاَ أنَزْلِناَ مُنزَلاً مُباَركَا وَأنَتَ خَيرُ المنُزْلِيِنَ رَبنَّآَ اتِۢناَ فِي الدُّنيَا حَسَنةَ وَفِي الاْۢخِرةِ حِسَنةَ وَقِناَ عَذَابَ الناَّرِ، وَصَلۢى اللهُّۢ عَلۢى سَ ِّيدِنَا مُحَمَّدٍ وَالِه وَصَحْبِه أجْمَعِيْنَ، وَالْحَمْدُ للهِ ر ِّبَ الْعالمَيِنَ',
        latin: 'Alhamdu lillahil azizil ghaffaar, al halimus sattaar, asy-hadu al laa ilaaha illallaahul waahidul jabbar, wa asy-hadu anna sayyidanaa wa habibanaa muhammadar rasuulullaahi allamanal ihtiyaa-tha li nanjuwa minal akh-thaar. Fa shalawaatullaahi wa salaamuhu alaihi wa aalihi wa shahbihil akh-yaar, ammaa ba du.Bismillaahir rahmaanir rahim Alhamdu lillaahi rabbil aalamin Allaahumma shalli wa sallim wa baarık alaa sayyıdinaa muhamadinil faatihi limaa ugh-liqa wal khaatami limaa sabaqa wan naa-shiril haqqi bil haqgi wal haadi ilaa shiraathikal mustaqim, shllallahu alathi wa alaa aalihi wa ash-haabihi haqga qadrihi wa miqdaarihil a-zhim Allaahumma innaa na uu-dzubika minal hammi wa hazani, wa na udzu bika minal ajzi wal kasali wa na uu-dzu bika minal jubni wal bukh-li wa na  uu-dzu bika min ghalabatid daini wa qahrir rijaal Allaahummakfinaa bi halaalika a haraamika wagh-ninaa bi fadh-lika amman siwaak Allaahummagh- fir lanaa dzunuubanaa wadz-hib ghai-zha quluubinaa wa ajirnaa minasy syai-thaan Rabbana anzilnaa munzalam mubaarakaa, wa anta khairul munzilin. Rabbana aatinaa fid dun-yaa hasanah, wa fil aa-khirati hasanah wa qinaa a dzaaban naar Wa shallallaahu alaa sayyidinaa muhammadiw wa aalihi wa shahbihi ajma in, walhamdu lillahi rabbi aalamin',
        arti: 'Artinya "Segala puji bagi Allah yang Maha Perkasa lagi Maha Pengampun. Aku bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Esa lagi Maha Memaksa. Dan aku bersaksi bahwa penghulu kami, kekasih kami yaitu Nabi Muhammad adalah utusan Allah yang telah mengajarkan kepada kami untuk waspada dari hal-hal yang membahayakan. Shalawat dan salam semoga tercurah kepada beliau, keluarga dan para sahabat yang terpilih. Adapun sesudah itu.Bukti Dengan nama Allah yang Maha Pengasıh lagi Mah Penyayang Segala puji bagi Allah Tuhan semesta alamY Allah, curahkanlah rahmat, salam, dan keberkahan kepad penghulu kami yaitu Nabi Muhammad yang merupaka pembuka sesuatu yang terkunci, penutup sesuatu yan Injil. penolong kebenaran, dengan kebenara penunjuk ke arah-Mu yang lurus Semoga Allah memberi curahkan rahmat kepada Beliau, juga kepada keluarga d para sahabarnya sepenuhnya dengan hak kekuasaan-Nya dan kekuasaan- Nya yang agung Ya Allah, yang kami lindungi kepada-Mu dari duka dan susah dan berlindung kepada-Mu dari sifat lemah dan malas; dan berlindung dari-Mu dari ketakutan dan sifat pelit; dan juga berlindung kepada-Mu dari beratnya utang dan penindasan orang. Ya Allah, cukupkan-lah kami dengan yang dihalalkan olch-Mu, jauh dari yang Engkau haramkan; kayakanlah kami dengan keutaman-Mu dari mengharap untuk selain Engkau. Ya Allah, ampunilah kami akan dosa-dosa kami dan hilangkanlah hawa amarah didalam hati kami, dan jauhkanlah kami dari gangguan syctan. Wahai Tuhan kami, tempatkanlah kami di tempat yang diberkati, dan Engkau adalah sebaik-baiknya yang memberikan tempat. Wahai Tuhan kami, berilah kami di dunia dan membantu di akhirat dan peliharalah kami dari siksa api neraka. Semoga Allah senantiasa mencurahkan rahmat kepada junjungan kami yaitu Nabi Muhammad, dan kepada seluruhnya. Segala puji bagi Allah Tuhan semesta alam ".',
    }
]