export default[
    {
        user: 'doa1',
        subject:  'Doa Pengajian',
        isi:'الْحَمْدُ للهِّۢ الَّذِيْ أنْعَمَ عَلَينْاَ بِنِعْمَةِ الإِيمَانِ وَالإِسْلاَمِ وَهِيَ أعْظمَ النِّعَمِ، أشْهَدُ أْنْ لآ إلِۢهَ إلِاَّ اللهُّۢ الراَّفِعُ الْحَكَمُ، وَأشْهَدُ أنَّ مُحَمَّدًا عَبدْهُ وَرسُوْلُهُ أشْرفُ الأنَامِ، صَلَوَاتُ اللهِّۢ وَسَلاَمُهُ وَبرَكَاتُهُ عَلَيْه وَعَلٓى الِۢ ِه وَصَحْبِه الْكِراَمِ، أمَّاَ بَعْدبِسْمِ اللهِّۢ الرحَّمۢنِ الرحِّيمِ، الْحَمْدُ للهِۢ ر ِّبَ الْعَالمَيْنَ، الَلّۢهُمَّ صَل صَلاَةً كا ِمَلَةً وَسَ ِّلِمْ سَلامًا تَامًّا عَلۢىِ سَ ِّي ِدنَا مُحَمَّ ٍد الَّ ِذِيْ تنَحَلُّ بِه الْعُقَدُ وَتنَفْرِجُ بِه الْكُربَ وَتقْضۢى بِه الْحَوَآ ِئجُ وَتنُاَلُ بِه الرغَّآ ِئبُ وَحُسْنُ الْخَوَاتِمِ وَيُسْتسَقَى الْغَمَامُ بِوَجْهِه الْكَرِيمِ وَعَلٓى آلِه وَصَحْبِه فِيْ كُ ِّل لمَحْة وَنفََسٍ بِعَدَدِ كُِّ ل مَعْلُومٍ لَكَ، رَبنَّاَ هَبْ لَناَ مِنْ أزَْوَاجِناَ وَذ ِّرُيَّاتِناَ قُرةََّ أعَْيُنٍ وَاجْعَلْناَ للِْمُتقَِّينَ إمَِامًا، رَبنَّاَ آتِناَ فِي الدُّنيَْا حَسَنةًَ وَفِي الآْخِرَةِ حَسَنةًَ وَقِناَ عَذَابَ الناَّرِ وَالْحَمْدُ للهِِّۢ ر ِّبَ الْعَالمَيِْنَ',
        latin:'Alhamdu lIllaahil la-dzii an ‘ama ‘alainaa bi ni’matil iimaani wal islaami wa hiya a’zhamun  ni’am. Asy-hadu anna muhammadan ‘abduhu wa rasuluhu asy-raful anaam. Shalawaatullahi wa salamuhu wa barakatuhu ‘alaihi wa ‘alaa aalihi wa shahbihil kiraam, ammaa ba’du.Bismillahirrahmanirrahim. Alhamdulillahi rabbil ‘aalamiin. Allaahumma shalli shalaatan(g) kaamilataw wa sallim saalaaman taamman ‘alaa sayyidinaa muhammadinil la-dzii tanhallu bihil ‘uqadu wa tanfariju bihil kurabu wa tuq-dhaa bihil hawaa-iju wa tunaalu bihir ra-ghaa-ibu wa husnul khawaatimi wa yustasqal ghamaamu bi wajhihil kariimi wa ‘alaa aalihi wa shahbihi fii kulli lamhatiw wa naafasim bi’adadi kulli ma’luumil lak(a). Rabbanaa hab lanaa min azwaajinaa wa dzurriyyaatina qurrata a’yuniw waj’alnaa lilmuttaqiina imaamaa. Rabbanaa aatinaa fid dun-yaa hasanah wa qinaa ‘a-dzaaban naar. Walhamdulillahi rabbil ‘aalamiin.',
        arti:'“Segala puji bagi Allah yang telah memberikan nikmat kepada kita dengan nikmat iman dan Islam, dan itulah seutama-utama nikmat. Aku bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Meninggikan lagi Yang Maha Menetapkan Hukum. Dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya yang merupakan seutama-utama manusia. Rahmat, salam dan berkah Allah semoga tetap tercurah keharibaan beliau SAW, keluarga serta para sahabatnya yang mulia. Adapun sesudah itu”.“Dengan nama Allah yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah Tuhan semesta alam. Ya Allah, curahkanlah rahmat dan keselamatan yang sempurna kepada junjungan kami yaitu Nabi Muhammad, semoga terurai dengan berkahnya semua buhulan, dilepaskan dari segala macam kesusahan, ditunaikan segala macam kebutuhan, tercapai segala macam keinginan dan memperoleh husnul khatimah (akhir yang baik), dicurahkan air hujan rahmat disebabkan berkah pribadinya yang mulia. Juga rahmat dan keselamatan tersebut dicurahkan kepada keluarga dan para sahabatnya disetiap kedipan mata dan hembusan nafas, bahkan sebanyak pengetahuan Engkau. Wahai Tuhan kami, anugerahkanlah kepada kami dari istri - istri kami dan keturunan kami suatu pemandangan yang menyejukkan mata, dan jadikanlah kami sebagai pemimpin orang – orang yang bertaqwa. Wahai Tuhan kami, berilah kami kebaikan di dunia dan di akhirat, dan peliharalah kami dari siksa neraka. Segala puji bagi Allah Tuhan semesta alam”.',
        
        
    },
    {
        user: 'doa2',
        subject:  '',
        isi:'',
        latin:'',
        arti:'',
        
    },
    {
        user: 'doa3',
        name: 'duduk',
        subject: 'doa duduk'
        
    },
    {
        user: 'doa4',
        name: 'berdiri',
        subject: 'doa berdiri'
    },
    {
        user: 'doa19',
        subject: 'doa amar ma ruf nahi mun kar,isra mi raj,dll',
        isi:'  الْحَمْدُ لِلهِ خَالِقِ الأْنَامِ وَحَاكِمِ الْحُكَّامِ وَعَاجِلِ النوُّر وَالظَّلامِ اشَهَدُ انَ لاۤ اِلٰهَ اِلاَّ اللهُ ذُو الْجَلاَلِ وَالإِكْراَمِ السَّلامَ، وَأشْهَدُ أَّنَّ مُحَمَّدًا رسُوْلُ اللهِّۢ المْبَعُوْثُ بِشَراَئِعِ الإِسْلامِ الَلّۢهُمَّ صَ ِّل عَلۢى خَيرْ الأْنَامِ، وَعَلٓۢى الِۢه وَأصَحَابِه الْكِراَمِ ، وَعَلَيْناَ مَعَهُمْ إلِۢى يوَمِ الْقِيَامَة أمَا بَعْدُ أعَوْذُ بِاللهِّۢ مِنَ الشَّيْطَانِ الرَّيمْ، بِسْمِ اللهِ الرحْمَنِ ال ِّرحِيمِ الْحَمْدُ للِهِ ر ِّبَ الْعَالمَيْنَ، الَلّۢهُمَّ صَ ِّل عَلۢى مُحَمَّدٍ ، صَلاَةً مُوْصِلَةً اِلَيْه جَامِعَةً عَلَيْه يتَلُوْهاَ الِّ لسَانِ وَيتَ ِصَّلُ بِ ِعلْ ِمهَا الجَناَنِ وَتَنبْ ِعَثُ أسَراَرهَاِفى الارَكَانِ فتَجَمَعُ القَلْبَ عَلىَ شُهُوْدِهِ وَالسَرَّ عَلَى نفُوُدِهِ وَالجَوَارحَ عَلۢى تَحَمُّلِ ادَٓاءِمَا تُحُ ِّملَتْ وَال ِّصدْقَ فِيْ مُعَامَلة مَنْ عَامَلَتْ وَعَلىۢٓ الِۢه الكِراَمِ وَاصَحَابِه الاْعْلامِ الَلهُمَّ ن ِّوَرْ قُلُوْبنَاَ وَاشْرحْ صُدُوْرنَا بِرحْمَ ِتكَ يۢٓاارَحَمَ الرَّا ِح ِميْنَ، اللّۢهُمَّ إِنَّا نَعُوْذُ بِكَ أنَ تزَلَّ أقْدَامَناَ عَلۢى ال ِّصراَ ِطِفيْ الناَّرِ يوَمَ تزَلَّ أقْدَامُ المنُاَ ِف ِقيْنَ وَالمْشُر ِكِيْنَ، رَبنَّاَ نَ ِّجناِمنَ الْقَوْمِ الظَّ ِالمِيْنَ، اللّۢهُمَّ نَعْت ِذَرُ إلَيْكَ ممَّا صَنعَ هٓؤُۢلا ِءٓۢ وَتبَرْئُ إلَيْكَ ممَّا صَنعَ هءُٓۢلا ِءۢٓ، رَبنَّآَ اتِۢناَ في الدُّنيْا حَسَنةً وَفِي الاْۢخِرةَ حَسَنةً وَقِناَ عَذَابَ الناَّرِ، يَا عَزِيْزُ يَا غَفَّارُ إنَّكَ عَلۢى كُ ِّل شَيءْ قَدِيْرٌ  وَالْحَمْدُ للهِ ر ِّبَ الْعالمَيِنَ ',
        latin:'Alhamdu lilaahil la-dzi la syarala fid dun-yaa wal aakhirati illaa syarata haa atih, asy-hadu al laa laaha ilallasho wahdahu laR syarika lah, was asy hadu anna muhammadan abduhu wa rasulauh. Allahumma shali alaa sayyidinaa muhammadiw wa alaa aalihi wa ash -haabih, ammaa ba du , A uu-dzu billaahi minasy syai thaanir rajim Bismillaahir rahmaanir rahim Alhamdu tillaahi rabbil aalamin Allaahumma shalli wa sallim alaa muu shilatan ilaihi jaami or alaihi yatluuhai lisaanu wa yatta shilu bi imihal janaanu wa tamba tsu asraaruhaa fil arkaani ta tajma ul galba alaa syuhuudihi was sirra alaa nufuu-dzihi wat jawaariha alaa tahammuli adaa-i maa tuhummilat wash shidga fi mu aamaiati man aamalat wa alaa aalihil kiraami wa ash haabihil a laam Allaahumma nawwir qulubanaa wasy rah shuduuranaa bi rahmatika yaa arhamar raahimiin Allaahumma innaa na uu-dzu bika an tazilla aqdaamanaa alash shiraathi fin naari yauma tazilla aqdaamul munaafiquna wal musy rikiin Rabbanaa najjinaa minal qaumizh zhaalimin Allaahumma na ta dziru ilaika mimmaa shana a haa-ulaa-iwa rabra u ilaika mimmaa shana a haa-uulaa-i Rabbanaa aatina fid dun yaa hasanah, wa fil aa khirati hasanah, wa qinaa a dzaaban naar yaa azizu yaa ghaffaar innaka alaa kulli syai ing qadir Walhamdu lillaahi rabbil aalamin',
        arti:'Artinya:" Segala puji bagi Allah yang tiada kemaliaan di dunia dan di akhirat selain kemuliaan untuk taat kepada-Nya. Aka bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Esi. tiada sekutu bagi-Nya. Dan aku bersaksi bahwa Nabi Muhammad adalah hamba dan utusan-Nya. Ya curahkanlah rahmat kepada Nabi Muhammad, keluarga dan para sahabatnya. Adapun sesudah itu , Aku berlindung kepada Allsh daxi segala godaan syetan yang terkurtok Dengan nama Allah yang Maha Pengasih lagi Maha Penyayang Segala puji bag: Allah Tuhan semesta Alam Ya Allab, corahkanlah rahmat dan salam kepada junjungan kami yaitu Nabi Muhammad, rahmat yang sampai kepadanya, kumpul di atas, yang mana lisan membacanya vang menimbulkan rabasia rahasianya di dalam semua rukun lalu dapat mengumpulkan hari manusia atas pensalksiannya dan rahasia atas kelangsungannya dan anggota-anggota hadan atas tanggungan sampa ada yang ditanggung, dan kejujuran di dalam perbuatan orang yang berbuat.Shalawat dan salam semoga tercurah pula kepada keluarga beliau yang mulia dan para sahabatnya yang besar Ya Allah, berikanlah cahaya untuk hati kamı, dan lapangkanlah dada kansi discbablan memperoleh rahmat Ma wahai Tuhan yang paling penyayang Ya Allah, sesungguhnya kami berlindung kepada- Mu dari tergelincirnya kakikami di atas jalan di neraka pada harı ketika kaki kaku orang munafik dan orang-orang musynk tergelinair Wahai Tuhan kami, selamatkanlah kami dan orang orang yang zalim Ya Allah, sesungguhnya kami memobon kepada-Mu keselamatan dan perbuatan mereka dan kami memohon dijauhkan dari perbuatan mereka.Wahai Tuhan kami berilah kami kebaikan di dunia, dan kebaikan diakhirat dan peliharalah kami darı siksa neraka, wahai Tuhan yang Maha Perkasa lagi Maha Pengampun, sesungguhnya Engkau Maha Kuasa atas segala sesuaru Segala puji bagi Allah Tuhan semesta alam".',
    },
    {
        user: 'doa20',
        subject: 'doa acara kajian rutin,ulang tahun,dll',
        isi:'الْحَمْدُ لِلهِ الَّذِيْ لاَ شَرفَ فِيْ الدُّنيْا وَالاۢخِرةَ إلِاَّ شَرفَ طاَعَتِهِ، أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ وَحْدَهُ لاَ شَرِيْكَ لَهُ، وَأشَهَدُ أنَ مُحَمَّدًا عَبدُهُ وَرسُوْلُهُ، الَلّۢهُمَّ صَ ِّل عَلۢى سَ ِّيدِنَا مُحَمَّدٍ، وَعَلۢٓى الِۢه وَأصَحَابِه الْكِراَمِ، وَعَلَينْاَ مَعَهُمْ إلِۢى يوَمِ الْ ِقيَامَة، أمَا بَعْد بِسْمِ اللهِ الرحَّمَنِ الِّرحِيمِ. حَمْدَ الشَّاكِرِيْنَ حَمْدَ الناَّعِمِيْنَ حَمْدًا حَمْدًا وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ، الَلَّهُمَّ صَ ِّل وَسَ ِّلمْ وَبَاركْ عَلۢى سَ ِّيدِنَا مُحَمَّدٍ وَعَلٓى الِۢ سَ ِّي ِدنَا مُحَمَّ ٍد، صَلاَةً وَسَلامَةً وَبرَكَةً دَٓا ِئمَةً مُسْت ِمَرةً تَدُوْمُ بِدَوَ ِامكَ وَتبَقْۢى بِبقَآ ِئكَ وَتَخْلُدُ بِخُلُوْ ِدكَ ولَاَ غَايَةَ لَهَا دُوْنَ مَرضَاتِكَ ولَاۢ جَزَاءَ لِقَائِلهَا وَمُضَ ِّليْهَا غَيرْ جَنتَّكَ وَالنظَّرَ إلِۢى وَجْهِكَ الْكَرِيمِ، الَلّۢهُمَّ اغْفِرْ لَناَ خَطِيئْتَنَاَ وَجَهْلَناَ وَإسْراَفنَاَ فِيْ أمُوْرنَا وَمَٓا أنَتْ أعَلَمُ بِه مِناَّ، الَلّۢهُمَّ رَبنَّاَ اغْفِرْ لَناَ وَلوَالدَينْاَ وَارحَمْهُمَا كَمَا رَبيَانَا صِغَاراً، الَلّۢهُمَّ إنَّا ضَعِيْفٌ فقَ ِّونَا وَإنَّا ذلَيْلٌ فَأعِزَّنَا وَإنَّا فقَيرْ فَأغْنِناَ يٓۢا أرَحَمَ الراَّحِمِيْنَ، الَلّۢهُمَّ أرَنَا الْحَقَّ حَقًّا وَارْزُقْناَ اتِّباَعَهُ وَأرَنَا الْباَ ِطلَ بَا ِطلاً وَارْزقْناَ اجْ ِتناَبَهُ، الَلَّهُمَّ إنَّا نَعُوذُ بِكَ مِنْ جَهْدِ البلَاءَ، وَدَركَ الشَّقَاءِ، وَسُوءِ القَضَاءِ، وَشَمَاتَة الأعَدَاءِ، رَبنَّآَ اتِۢناَ فِي الدُّنْيَا حَسَنةً وَفِي الاْۢخِرةَ حَسَنةً وَقِناَ عَذَابَ الناَّرِ، وَالْحَمْدُ للهِّۢ ر ِّبَ الْعَالمَيْنَ',
        latin:'Alhamdu lilaahil la-dzi laa syarafa fid dun-yaa wal aakhirati illaa syarafa haa atih, asy-hadu al laa ilaaha ilallaahu wahdahu laa syarika lah, was asy hadu anna muhammadan abduhu wa rasulauh. Allahumma shali alaa sayyidinaa muhammadiw wa alaa aalihi wa ash -haabih, ammaa ba du Bismillaahir rahmaanir rahiim Hamdasy syaakirin hamdan naa imiin, hamday yuwaatii ni amahu wa yukaafi mazidah, rabbanaa lakal hamdu kamaa yamba ghi t jalaali wajhikal kariimi wa a zhiumi sulthaanika Allaahumma shalli wa sallim wa baarik alaasayyidinaa muhammad wa alaa aali sayyidinaa muhammad shalaatan wa salaamatan wa barakatan daa imatan mustamirratan taduumu bidawaamika wa tabqaa bi baqaa ika wa takh ludu bi khuluudika wa laa ghaayata lahaa duuna mar dhaatika wa laa azaa a li qaa ilihaa wa mu shallihaa ghaira jannatika wan na zhan ilaa wajhikal karim Allaahummaghtir lanaa kha thiatanaa wa jahlanaa wa israatanaa fi umuurinaa wa maa anta a lamu bihi minnaa Allaahummaghtirlanaa wa waalidiinaa warhamhum kamaa rabba yaanaa shi ghaaraa Allaahumma innaa dha ifun fa gawwinaa wa innaa dzalilun fa a izzanaa wa innaa taqiirun fa agh ninaa yaa arhamar raahimin Allaahumma arinal haqga haqqan warzuqnat tibaa ah wa arinal baa thila baa thiian warzuqnajtinaabah Allaahumma innaa na uu dzu bika min jahdil bataa iwa darkisy syaqaa i wa suu il qa dhaa i wa syamaatatil a daa Rabbanaa aatinaa fid dun yaa hasanah wa fil aakhirati hasanah, wa qinaa a dzaaban naar Walhmadu lillahi tan aalamin',
        arti:'Artinya : "Segala puji bagi Allah yang tiada kemaliaan di dunia dan di akhirat selain kemuliaan untuk taat kepada-Nya. Aka bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Esi. tiada sekutu bagi-Nya. Dan aku bersaksi bahwa Nabi Muhammad adalah hamba dan utusan-Nya. Ya curahkanlah rahmat kepada Nabi Muhammad, keluarga dan para sahabatnya. Adapun sesudah itu rabbi Dengan nama Allah yang Maha Pengasih lagi Maha 1 penyayang Sebagimana orang orang yang bersyukur. dan orang yang memperoleh nikmar sama memuj, dengan yang sebanding dengan nikmat-nikmat Nya dan menjamin tambahnya Wahai Tuhan kami, bagi Mu segala pui sebagaimana apa yang patut bagi keluhuran Zat Mu mulia dan keagungan kekuasaan-Mu Ya Allah. curahkanlah rahmat, salam dan keberkahan kepada junjungan kamı yaitu Nabi Muhammad beserta keluarganya rahmat, salam dan berkah yang terus-menerus, a kekal karena kekekalan-Mu ia abadi karena keabadian Mu, ta langgeng karena kelanggengan-Mu, tiada ujung baginya tanpa keridhaan-Mu dan tiada balasaan bagı pembacanya dan yang memintakan rahmat selain surga-Mu dan memandang wajah-Mu yang Mulia Ya Allah, ampunilah kami, kesalahan-kesalahan kami. kebodohan kami, segala sesuatu yang menjadi urasan kami yang melampau batas serta segala apa yang mana Engkau lebıh mengetahui lebih banyak tentang kami. Ya Allah, ampunilah kami dan kedua orang tua kami, rahmatilah mereka telah mendidik kami di waktu kecil. Ya Allah, sesungguhnya kami adalah lemah, maka kuatkanlah kami, nyata kami hina, maka muliakanlah kami, dan nyata kami fakir (miskin), maka kayakanlah kami wahai Tuhan yang paling penyayang. Ya Allah, tunjukkanlah kepada kami yang benar itu benar, dan berilah kami Karena sesungguhnya tidak ada yang dapat menjauhkannya selain Engkau. Ya Allah, jadikanlah kami orang yang bersyukur, jadikanlah kami orang yang sabar, dan kami adalah orang-orang yang kecil dalam pandangan mata kami dan besar dalam pandangan manusia. Tuhan kami, berilah kami baik di dunia dan kebaikandi akhirat, dan peliharalah kami dari siksa neraka Maha suci Tuhanmu, Tuhan yan Maha Perkasa terhadap apa yang mereka sifatkan Keselamatan semoga tercurah kepada rasul-rasul, dan segala puji bagi Allah Tuhan semesta alam. ".',
    },
    {
        user: 'doa21',
        subject: 'doa acara silaturahmi,dll',
        isi: 'الْحَمْدُ لِلهِ الْعَزِيزْ الْغَفَّارِ الْحَليِمِ السَّتاَّرِ، أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ الْوَاحِدُ الْجَباَّرُ، وَأشْهَدُ أنَّ سَ ِّيدَنَا وَحَبِيبْنَاَ مُحَمَّدًا رسُوْلُ اللهِّۢ عَلَّمَناَ الاِحْتِيَاطَ لِننَجْوِمنَ الاَخْطَارِ، فَصَلَوَاتُ اللهِّۢ وَسَلامُهُ عَلَيْه وَالِۢه وَصَحْبِه الاَخْيَارِ، أمَّا بَعْدُ بسْمِ اللهِ الرَّحْمَنِ ال ِّرحِيمِ. الْحَمْدُ للهِ ر ِّبَ الْعَالمَيْنَ الَلَّهُمَّ صَ ِّل وَسَ ِّلمْ وَبَاركْ عَلۢى سَي ِّ ِدنَا مُحَمَّ ٍد الْفَا ِتحِ لماَ أغْلِ-قَ وَالْخَا ِتمِ لماَ سَبقَ وَالِناَّصرِ الْحِ ِّق بِالْح ِّق وَالِهَا ِديٓ إلِۢى صراَ ِطكَ المْسْت ِقَيمْ، صَلّۢى اللهُّۢ عَلَيْه وَعَلٓى الِۢه وَأصْحَابِه حَقَّ قَدْرهِ وَمِقْدَارهِ الْعَظِيمْ، الَلّۢهُمَّ إنِّا نَعُوْذُ بِكَ مِنَ الْهَ ِّم وَالْحَزَنِ وَنَعُوْذُ بِكِ منَ الْعَجْزِ وَالْكَسَلِ وَأعُوذُ بِكَ منَ الْجُبْنِ وَالْبخُلِ وَأعُوذُ بِكَ مِنْ غَلَبةَ الدَّيْنِ، وَقَهْرِ ال ِّرجَالِ، الَلَّهُمَّ اكْفِناَ بِحَلالِكَ عَنْ حَراَمِكَ وَأغَنِناَ بِفَضْلكِ عَمَّنْ سِوَاكَ، الَلّۢهُمَّ اغْفِرْ لَناَ ذنُوْبنَاَ وَاذْهِبْ غَيظْ قُلُوْبِناَ وَاجِرنْا مِنَ الشّيْطَانِ، رَبنَّاَ أنَزْلِناَ مُنزَلاً مُباَركَا وَأنَتَ خَيرُ المنُزْلِيِنَ رَبنَّآَ اتِۢناَ فِي الدُّنيَا حَسَنةَ وَفِي الاْۢخِرةِ حِسَنةَ وَقِناَ عَذَابَ الناَّرِ، وَصَلۢى اللهُّۢ عَلۢى سَ ِّيدِنَا مُحَمَّدٍ وَالِه وَصَحْبِه أجْمَعِيْنَ، وَالْحَمْدُ للهِ ر ِّبَ الْعالمَيِنَ',
        latin: 'Alhamdu lillahil azizil ghaffaar, al halimus sattaar, asy-hadu al laa ilaaha illallaahul waahidul jabbar, wa asy-hadu anna sayyidanaa wa habibanaa muhammadar rasuulullaahi allamanal ihtiyaa-tha li nanjuwa minal akh-thaar. Fa shalawaatullaahi wa salaamuhu alaihi wa aalihi wa shahbihil akh-yaar, ammaa ba du.Bismillaahir rahmaanir rahim Alhamdu lillaahi rabbil aalamin Allaahumma shalli wa sallim wa baarık alaa sayyıdinaa muhamadinil faatihi limaa ugh-liqa wal khaatami limaa sabaqa wan naa-shiril haqqi bil haqgi wal haadi ilaa shiraathikal mustaqim, shllallahu alathi wa alaa aalihi wa ash-haabihi haqga qadrihi wa miqdaarihil a-zhim Allaahumma innaa na uu-dzubika minal hammi wa hazani, wa na udzu bika minal ajzi wal kasali wa na uu-dzu bika minal jubni wal bukh-li wa na  uu-dzu bika min ghalabatid daini wa qahrir rijaal Allaahummakfinaa bi halaalika a haraamika wagh-ninaa bi fadh-lika amman siwaak Allaahummagh- fir lanaa dzunuubanaa wadz-hib ghai-zha quluubinaa wa ajirnaa minasy syai-thaan Rabbana anzilnaa munzalam mubaarakaa, wa anta khairul munzilin. Rabbana aatinaa fid dun-yaa hasanah, wa fil aa-khirati hasanah wa qinaa a dzaaban naar Wa shallallaahu alaa sayyidinaa muhammadiw wa aalihi wa shahbihi ajma in, walhamdu lillahi rabbi aalamin',
        arti: 'Artinya "Segala puji bagi Allah yang Maha Perkasa lagi Maha Pengampun. Aku bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Esa lagi Maha Memaksa. Dan aku bersaksi bahwa penghulu kami, kekasih kami yaitu Nabi Muhammad adalah utusan Allah yang telah mengajarkan kepada kami untuk waspada dari hal-hal yang membahayakan. Shalawat dan salam semoga tercurah kepada beliau, keluarga dan para sahabat yang terpilih. Adapun sesudah itu.Bukti Dengan nama Allah yang Maha Pengasıh lagi Mah Penyayang Segala puji bagi Allah Tuhan semesta alamY Allah, curahkanlah rahmat, salam, dan keberkahan kepad penghulu kami yaitu Nabi Muhammad yang merupaka pembuka sesuatu yang terkunci, penutup sesuatu yan Injil. penolong kebenaran, dengan kebenara penunjuk ke arah-Mu yang lurus Semoga Allah memberi curahkan rahmat kepada Beliau, juga kepada keluarga d para sahabarnya sepenuhnya dengan hak kekuasaan-Nya dan kekuasaan- Nya yang agung Ya Allah, yang kami lindungi kepada-Mu dari duka dan susah dan berlindung kepada-Mu dari sifat lemah dan malas; dan berlindung dari-Mu dari ketakutan dan sifat pelit; dan juga berlindung kepada-Mu dari beratnya utang dan penindasan orang. Ya Allah, cukupkan-lah kami dengan yang dihalalkan olch-Mu, jauh dari yang Engkau haramkan; kayakanlah kami dengan keutaman-Mu dari mengharap untuk selain Engkau. Ya Allah, ampunilah kami akan dosa-dosa kami dan hilangkanlah hawa amarah didalam hati kami, dan jauhkanlah kami dari gangguan syctan. Wahai Tuhan kami, tempatkanlah kami di tempat yang diberkati, dan Engkau adalah sebaik-baiknya yang memberikan tempat. Wahai Tuhan kami, berilah kami di dunia dan membantu di akhirat dan peliharalah kami dari siksa api neraka. Semoga Allah senantiasa mencurahkan rahmat kepada junjungan kami yaitu Nabi Muhammad, dan kepada seluruhnya. Segala puji bagi Allah Tuhan semesta alam ".',
    },
    {
        user:'doa22',
        subject:'doa acara nuzulul quran,dll',
        isi: 'الْحَمْدُ لِلهِ الَّذِيْ خَلَقَناَ فِيْٓ أحْسَنِ تقَوِيمْ، أشَهَدُ أنْ لآ إلِۢهَ إلِاَّ اللهُّۢ الْجَليِلُ الْكَرِيمُ، وَأشَهَدُ أنَّ مُحَمَّدًا رَسِوْلُ اِللهِّۢ خَيرُ مَنِ تَأدَّبَ بِأدَاِبِ الْقُراْنِۢ الْكَرِيمْ، وَالصَّلاَةُ وَالسَّلامُ عَلَيْه وَالِۢه وَاصْابِه إلِۢى سَاعَة الْقِيَامِ، أمَّا بَعْدُ ِسْمِ اللهِ الرحْمَنِ ال ِّرحِيمِ. الْحَمْدُ للهِ ر ِّبَ الْعَالمَيْنَ، الَلّۢهُمَّ صَ ِّل عَلَى سَ ِّي ِدنَا مُحَمَّ ٍد صَلاَةً تنُجْيِنْاَبِهَا منْ جَ ِميْعِ الْاَهْوَالِ وَالْآفَا ِت، وَتقْ ِضىْ لَناَ بِهَا جَ ميْعَ الْحَاجَا ِت، وَتُطَ ِّهرنَا بِهَا منْ جَ ِميْعِ السَّ ِّيئاَ ِت. وَترَفْعُناَبِهَا عندَكَ اعْلَى الدَّرجَا ِت. وَتبُ ِّلَغُناَ بِهَٓا اقْصَى الْغَيَا ِتِ منْ جَ ِميْعِ الْخَيرْاَ ِت فِى الْحَيَاةِ وَبَعْدَ المْمَاتِ، الَلّۢهُمَّ اخْتِمْ لَناَ بِخَاتِمَة السَّعَادَةِ، وَاجْعِلْناَ مِنَ الَّذِيْنَ لَهُمُ الْحُسْنىۢ وَزِيَادَةً، بِجَاِهِ سَ ِّيدِنَا مُحَمَّدٍ صَلّۢى اللهُّۢ عَلَيْه وَسَلَّمَ ذيْ الشَّفَاعَة، وَعَلۢٓى الِۢه وَصَحْبِه ذَوِي السَّعَادَة، رَبنَّاَ ظلَمْناَ أنَفْسَناَ وَإنِ لَمْ تَغْفِرْ لَناَ وَترَحَمْناَ لَنكُوْنَنَّ مِنَ الْخَاسِرِيْنَ، رَبنَّاَ تقَبلَّ مِناَّ اِنَّكَ انَتَ السَّمِيعُ الْعَليِمْ وَتبُ عَلَينْاَ اِنَّكَ انَتَ التوَّابُ الرحَّيمُ، رَبنَّآَ اتِۢناَ فِي الدُّنيَا حَسَنةً وَفِي الاْۢخِرةَ حَسَنةً وَقِناَ عَذَابَ الناَّرِ، وَالْحَمْدُ للهِ رَ ِّب الْعالمِينَ',
        latin:'Alhamdu lillaahi la-dzii khalaqanaa fii ahsani taqwiim, asy-hadu al laa ilaaha llallaahul jalilul kariim, wa asy-hadu anna muhammadar rasuulullaahi khairu man ta-addaba bi adaabil qur-aanil kariim. Wash shalaatu was salaamu alaihi wa aalihi wa ash-haabihi ilaa saa atil giyaam, ammaa ba du .Bismilaahir rahmaanir rahiim Athamdu illaahi rabbil aalamin Allaahumma shalli alaa sayidinaa muhammad shalaatantunjinaa bihaa min jam itu ahwaali wal aafaat, wa taqdhi lanaa bihaa jami al haajaa wa tu-thahhiunaa bihaa min jamiis sayi-aat wa tarta unaa bihaa a lad darajaat, wa tuballi- ghunaa bihaa aq shal ghaayaat, min jami u khairaats fil hayaati wa ba dal mamaat Allaahummakh tim lanaa b khaatimatis sa aadah, waj alnaa minal la dzina lahumul husnaa wa ziyaadah, bi jaahi savyidinaa muhammadin shallallaahu alaihi wa sallama dzisy syafaa ah wa alaa aalihi wa shahbihi dzawis sa aadah Flabbanaa zhalamnaa anfusanaa wa il lam tagh-fir lanaa wa tarhamnaa la nakuunanna minal khaasurin Rabbanaa taqabbalminnaa innaka an tas samirul alim, wa tub alainaa innaka antai tawwaabur rahiim Rabbanaa aatinaa tid dun yaa hasanah, wa fil aa-khirati hasanah wa qinaa a -dzaabannaar, walhamdu ilaahi rabbil aalamin',
        arti:' Artinya: "Segala puji bagi Allah yang telah menciptakan kami dalanm bentuk yang sebaik-baiknya. Aku bersaksi bahwa tidak ada Tuhan selain Allah yang Maha Besar lagi Maha Mulia. Dan aku bersaksi bahwa Nabi Muhammad adalah utusan Allah sebaik-baik orang beradab dengan adab Al quran yang mulia. Shalawat dan salam semoga tercurah kepadanya, keluarga dan para sahabatnya sampai saat tiba hari kiyamat Adapun sesudah itu .Dengaan nama Allah yang Maha Pengasih lagi Maha Penyayang, Segala pui bagi Allah Tuhan semesta alam Ya Allah, curahkanlah rahmat kepada junjungan kami yairu Nabi Muhammad, yang dengan rahmar itu Engkau menyelamarkan kami dari ketakuran dan malapetaka yang Dengan rahmat itu pula Engkau memenuhi semuampu kami, yang berhubungan Engkau mensucikan kan gk kami dengan derajat yang setinggi-tinggi, dan dengan pula pula Engkau mengantar kami ke tempat yang palin ujung dari semua orang (hidup) di dunia dan (hidup Internet mati. Ya Allah, akhirilah kami dengan akhir yan bahagia; jadikanlah kami termasuk golongan orang yan hasilkan dan pertunangan dengan sebab-sebab Nabi Muhammad SAW yang memiliki syafaat dan juga keluarga dan para sahabatnya yang mempunyai kebahagian. Wahai Tuhan kami, nyata kami telał menganiaya kami tidak, Engkau kasih kami dan kami (tidak pula) Engkau kasihani kami, maka kami bisa menggunakan orang-orang yang merugi. Wahai Tuhan kami, terimalah kami, sesungguhnya Engkau adalah Maha Penerima tobat lagi Maha Penyayang. Wahai Tuhan kami, berilah kami Selamat di dunia dan demi akhirat dan peliharalah kami dari siksa neraka. Semua puji bagi Allah dari segala keburuk an, yang berhubungan Engkau mengan Tuhan semesta alam ".',
    },
    {
        user:'doa23',
        subject:'doa acara yang berhubungan dengan musibah,kebakaran,sakit,kemiskinan,dll',
        isi:'الْحَمْدُ لِلهِ المْحَمُوْدِ عَلۢى الْبأَسَْٓاءِ وَالضَّراَّء، المْعْبوْدِ فِيْ الاْقَطَارِ َالاَرجَاءِ، أشْهَدُ أنْ لآ إلِۢهَ إلِاَّ اللهُّۢ وَأشْهَدُ أنَّ مُحَمَّدًا رسُوْلُ اللهِّۢ خَتمُ الأْنبِيَٓاءِ، فَصَ ِّل وَسَ ِّلمْ عَلَيْهِ وَعَلۢٓى الِۢهِ وَصَحْبِهِ صَلاَةً وَسَلامَةً دَٓائِمَةً بِلاَ انقِضَاءِ، أمَّا بَعْدُ أعَوْذُ بِاللهِّۢ مِنَ الشَّيْطَانِ الرجِّيمْ، بِسْمِ اللهِ الرحَّمَنِ ال ِّرحِيمِ. حَمْدَ الشَّاكِرِيْنَ حَمْدَ الناَّعِمِيْنَ، حَمْدًا يوُافِى نِعَمَهُ وَيُكَافِى مَزِيدَهُ، يَارَبنَّاَ لَكَ الْحَمْدُ كَمَا ينَبْغِى لِجَلاَلِ وَجْهِكَ وَعَظِيمْ سُلْطَانِكَ، الَلّۢهُمَّ صَ ِّل عَلَى سَ ِّيدِنَا مُحَمَّدٍ وَعَلۢى الِۢ سَ ِّيدِنَا مُحَمَّدٍ فِيْ الاْۢخِرِيْنَ، وَصَ ِّل عَلَى سَ ِّيدِنَا مُحَمَّ ٍد وَعَلۢى الِۢ سَ ِّي ِدنَا مُحَمَّ ٍدِفيْ المْرُسَلِيْنَ، وَصَ ِّل عَلَى سَ ِّي ِدنَا مُحَمَّ ٍد وَعَلۢى الِۢ سَّي  ِدنَا مُحَمَّ ٍدِفيْ الملَا ِءَ الأْعْلۢى إلِۢى يوْمِ ال ِّديْنَ. الَلّۢهُمَّ اصْلِحْ لَناَ شَأنْنَاَ وَثَبِّتنْاَ بِالْقَوْلِ الثاَّبِتِ فيْ الْحَيَا ِة الدُّنيَا وَالاۢ ِخر ِةَ. الَلّۢهُمَّ إنِّا نَسْألَكَ الْفوْزَ عندَ الْقَضَٓا ِء وَمَناَزِلَ الشُّهَدَا ِء وَالْعَيْشَ السُّعَدَٓا ِء وَالنصّْرَ عَلۢى الأْعْدَٓاءِ. الَلّۢهُمَّ اجِرنَا مِنَ الناَّرِ وَادْخِلْناَ الْجَنةَّ مَعَ الْفَٓائِزِيْنَ وَزَ ِّوجْناَ مِنَ الْحُوْرِ الْعِيْنِ، وَصَلّۢى اللهُّۢ عَلۢى خَيرْ الأْنَامِ، وَعَلۢٓى الِۢ ِه وَصَحْبِ ِه إِلۢى يوْمِ الْ ِقيَامَ ِة، وَالْحَمْدُ للهِ ر ِّبَ الْعالمِينَ',
        latin:'Alhamdu lillaahil mahmudi alal ba saa-iwadh dharraa, alma buudi il aq thaari wal arjaa, asy-hadu al laa ilaa ha illallaahuwa asy-hadu anna muhammadar rasuulullaahi khatamur rusli wal ambiyaa, fa shalli wa sallim alalhi wa  alaa aalihi wa shahbihi shalaatan wa salaamatan daa-imatan bi lang qi-dhaa , ammaa ba du. Au -dzu billaahi minasy syai thaani rajim Bismillaahir vahmanir rahim Hamdasy syaakirin hamdan naa imin, hamday yuwaati nramahu wa yukaati mazidah, rabbanaa lakal hamdu kamaa yamba-gha i jalaa wajhikal karimi wa a zhiimi suithaanik Allaahumma shali alea vyiainaa muhammad wa alaa aali sayyidinaa muhammad fil awwalin hali alaa syyidinaa muhammad wa alaa aali sayyidina muhammad fi aa khirin, wa shalli alaa sayyidinaa muhammad wa alaa aa sayyidinaa muhammad tin nabiyyin, wa shalli alaa sayyidinaa muhammad wa alaa aali sayyidinaa muhammad i mala la laa ilaa yaumid din Allaahumma ash lih lanaa sya nanaa wa sabbit naa bil qaulits tsaabiti fil hayaatid dun yaa wal aa khirah Allaahumma innaa nas alukal fauza indal qa dhaa iwa manaazilasy syhuhadaa wa ai syas su adaa i wan nashra alal a daa Allahumma ajirnaa minan naar, wa zawwijnaa minal huuril in. Wa Shallalaalhu alaa khairil anaam wa alaa aalihi wa shahbihi ilaa yaumil giysam Wahamdu lillaahi rabbii aalamin',
        arti:'Artinya : "Segala puji bagi Allah yang terpuji atas kesempatan dan penderitaan, yang disembah karena curahan dan rahmar dan penuh harapan. Aku bersaksi bahwa tidak ada Tuhan selain Allah dan aku bersaksi bahwa Nabi Muhammad adalah utusan Allah yang menjadi penutup para rasul dan para Nabi Rahmat dan salam semoga tercurah kepada beliau, keluarga dan para sahabatnya, rahmat dan salam yang kekal tanpa keputusan. Adapun sesudah itu.Aku berlindung kepada Allah dari segala godaan syctan yaeg terkuruk dengan nama Allah yang Maha Pengasih lagi Maha Penyayang bagi orang-orang yang benyukur, dan orang yang memperolch nikmat sama dengan, dengan yang sebanding dengan nikmat-nikmat- Nya dan menjamin tambahnya. Wahai Tuhan kami, bagi-Mujaan puji apa yang diberikan untuk keluhuran Zat- Mu Mulia dan keagungan kekuasaan-Mu. Ya Allah, curahlkaniah rahmat kepada junjungan kami yaitu Nabi Muhammad bersama keluarga pada abad pertama. Dan curahkanlah rahmat kepada junjungan kami yaitu Nabi Muhammad beserta keluarga (abad-abad) terakhir Dan curahkanlah rahmat kepada junjungan kami yaitu Nabi Muhammad bersama keluarga di dalam Nabi-nabi. Dan curahkanlah rahmat kepada junjungan kami yaitu Nabi Muhammad bersama keluarga pada orang-orang yang terringg sampai hari kiamat. Ya Allah, perbaikilah hubungan kami. Pui yang gan perkataan yang tetap teguh baik di dunia maupun akhirat.Ya Allah, sebenarnya kami memohon kepada-Mu alan kebahagian di depan pengadilan dan tempat orang-orang yang mati syahid, juga penghidupan orang-orang yang bahagia dan pertolongan dalanm menghadapi musuh. Ya Allah. neraka dan masuldlanlah kami ke dalam surga orang-orang yang memperolch kemenar kanlah aku dengan bidadari yang menyenangkan membaca Semoga Allah senantiasa selamatkanlah kami dari Neraka dan masukkanlah kami kedalam surga bersama-sama orang-orang yang memperoleh kemenangan,serta kawinkanlah aku dengan bidadari yang menyenangkan pandangan.Semoga Allah senantiasa- mencurahkan rahmat untuk sebaik baik manusia (yaitu Nabi Muhammad ) keluarga dan para sahabat beliau sampai hari kiamat.segala puji bagi Allah Tuhan semesta alam".',
    },
    {
        user:'doa24',
        subject:'doa acara syukuran atas melimpahnya rizki',
        isi:'الْحَمْدُ لِلهِ الَّذِيْ خَلَقَ الاْنِسَانَ وَصَوَّرهُ مِنَ الْعَدَمِ، وَقَدَّرَ رِزقَهُ وَأجَلَهُ وَعَلَيْه بِكَأسِ المْنَوُنِ قَدْ حَكَمَ، وَقَضۢى عَلَيْ ِه إمَّا بِالشَّقَاوَةِ وَإمَّا بِالسَّعَدَةِ، أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ وَأشْهَدُ أنَّ مُحَمَّدًا رَسُوْلُ اللهِّۢ سَ ِّيدُ الْعَرَبِ وَالْعَجَمِ، الَلّۢهُمَّ صَ ِّل وَسَ ِّلمْ عَلَيْه وَالِۢ ِه وَأصَحَابِ ِه أهَلِ الْفَضْلِ وَالْكَرَمِ، أمّاَ بَعْدُ ِسْمِ اللهِ الرحَّمَنِ ال ِّرحِيْمِ. الْحَمْدُ للهِ ر ِّبَ الْعَالمَيْنَ الَلّۢهُمَّ صَّل وَسَ ِّلمْوَبَاركْ عَلۢى سَ ِّي ِدنَا مُحَمَّ ٍد النِوُّرِ الذَّا ِتيْ وَال ِّس ِّر السَّارِيِفيْ سَا ِئرِ الأسَمَا ِء وَال ِّصفَا ِت وَعَلۢٓى الِۢه وَصَحْبِه اجَمَ ِعيْنَ وَعَلَيِنْاَ مَعَهُمْ بِرحْمَتِكَ يۢٓا ارَحَمَ الراَّ ِح ِميْنَ بِسْمِ اللهِ الَّ ِذى لاَ يَضُرُّ مَعَ اسْ ِمه شَيءِفى الارَضْ ولَاَ فِى السَّمَاءِ وَهُوَ السَّميعُ العَليِمِ، الَلّۢهُمَّ ارْزقْناَ رِزقًا وَاسِعًا بِلاَ تَعَبٍ ولَاَ نَصَبٍ إنَّكَ عَلۢى كُ ِّل شَيءْ قَدِيرْ الَلّۢهُمَّ ر ِّضَناَ بِقَضَٓائِكَ وَبَاركْ لَناَ فِيمْا قُ ِّدرَ حَتّىۢ لاَ نُحِبَّ تَعْجيْلَ مَٓا اخَّرتَ ولَاَ تَأخْيرْ مَا عَجَّلْتَ، الَلَّهُمَّ ياَ غَ ِنىُّ  ياحَ ِميدُ  يَامُب ِدْئُ  يَامُ ِعيدُ  يَار ِحَيمْ  يَاوَدُوْدُ يَافَعَّالِلماَ يرُيدُ اغَنِنِىْ بِحَلالَكَ عَنْ حَراَمِكَ وَبِفَضْلكَ عَمَّنْ سِوَاكَ يَا كَرِيمْ يَا ذَا الْفَضْلِ الْعَظِيمِ يَا وَاسِعَ الْعَطَٓاءِ وَالْكَرمِ. رَبنَّآَ اتِۢناَ فِي الدُّنْيَا حَسَنةً وَفِي الاْۢخِرةَ حَسَنةً وَقِناَ عَذَابَ الناَّرِ، وَالْحَمْدُ للهِ ر ِّبَ الْعالمَيِنَ',
        latin:'Alhamdu lillaahil la-dzii khalaqal insaana wa shawwarahu minal adam, wa qaddara rizgahu wa ajalahu wa  alaihi bika sil manuu hakam, wa qa-dhaa alaihi immaa bisy syaqaawati wa immaa qad bissa aadah. Asy- hadu al laa ilaaha illallaahu wa anna muhammadar rasuulullaahi sayyidul arabi wal ajam. Allaahumma shalli wa sallim alaihi wa aalihi wa ash- haabihi ahlil fadh-li walkaram, ammaa ba du. Bismillaahir rahmaanir rahiim Alhamdu lilaahi rabbil aalamiin Allaahumma shalli wa sallim wa baarik alaa sayyidinaa muhammadinin nuuridz dzaati7 sirris saaru fi saa-iril asmaa-aku mencuci shifaati wa alaa aalihi wa shahbihi ajma di, wa alainaa ma ahum bi rahmatıka yaa arhamar raahimin Bismillaahil la -dzi laa ya-dhurru ma asmihil syai-un fil ar-dhi wa laa fis samaa-i wa huwas sami ul alim Allaahummarzugnaa rizqan waasi an bi laa ta abin wa laa na sha bin innaka alaa kulli syai ing qadir Allaahumma radh dhinaa bi qa-dhaa-ika wa baarık lanaa fimaa quddira hatta laa nuhibba ta jula maa akh-kharta wa laa ta khlira maa a jalta Allahumma yaa ghaniyyu yaa hamidu yaa mub di-u yaa mu idu yaa rahimu ya waduudu yaa fa  aalul limaa yuriidu agh-nina bi halaalika a haraamika wa bifadh-lika amman siswaaka yaa kariim yaa dzal fadh-lil a-zhimi yaa waasial aaa-i wal karam. Rabbanaa aatinaa fid dun-yaa hasanah, wa fil aa-khirati hasanah, wa qinaa a-dzaabar naar walhamdu lillaahi rabbil aalmiin',
        arti:'Artinya :  "Segala puji bagi Allah yang telah menciptakan manusia dan memberi bentuk kepadanya dari yang sebelumnya tidak ada. Allah menentukan rizki dan ajal manusia dan juga Allah memberikan karunia kepada manusia. Dia (Allah) menetapkan kepada manusia adakalanya dengan kesengsaraan dan adakalanya dengan kebahagiaan. Aku bersaksi bawa tidak ada Tuhan selain Allah dan bahwa Nabi Muhammad adalah utusan Allah yang menjadi penghulu bangsa Arab dan bangsa Ajam. Ya Allah, curahkanlah rahmat dan salam kepada beliau, keluarga dan para sahabatnya yang ahli keutamaan dan kemuliaan. Adapun sesudah itu.Dengan nama Allah yang Maha Pengasih lagi Maha Penyayang Segala puji bagi Allah Tuhan semesta alam. Ya Allah, curahkanlah rahmat , salam dan keberkahan kepada junjungan kami yaitu Nabi Muhammad cahaya Zat (Allah), dalam seluruh nama dan sifat juga tercinta untuk keluarga dan para sahabatnya semuanya kami bersama mereka adalah saya dan rahasia yang memiliki rahasia dan tercurah untuk menemukan rahmat-Mu wahai Tuhan yang paling penyayang Dengan nama Allah,Yang dengan menyebut nama Nya tidak ada sesuatupun yang baik di langit atau di bumi dan Dia adalah Maha Mendengar lagi Maha Mengetahui Ya Allah. berilah kamı rizki, yaitu rizki yang luas tanpa lelah atau sulit, sesungguhnya Engkau Maha Kuasa atas segala sesuatu Ya Allah, berilah keridhaan kepada kami terhadap apa yang telah ditetapkan sebagai tidak lagi penyegeraan terhadap apa yang Engkau akhirkan. dan tidak mengakhirkan apa yang Engkau segerakan Ya Allah yang Maha Kaya. Maha Terpuji, Maha Memulai. Maha Mengembalikan. Maha Pengasıh lagi Maha Penyayang, yang berbuar sekehendak-Nya, kayakanlah kamı dengan sesuatu yang Engkau halalkan dan jauh dari yang Engkau haramkan, dan dengan keutamaan-Mu ridak harapan untuk selain Engkau wahai Tuhan yang Mulia, yang memiliki keutamaan yang besar, yang luas pemberiannya lagi Maha Mulia Tuhan kami, berilah kami di dunia dan membantu di akhirat, dan peliharalah kamı dari siksa neraka Segala puji bagi Allah Tuhan semesta alam ".',
    },
    {
        user:'doa25',
        subject:'doa acara pengajian rutin,arisan,dll',
        isi:'الْحَمْدُ لِلهِ الْعَليِّ الْكَبِيرْ السَّمِيْعِ الْبصَيرْ، أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ الْعَليِمْ الْخَبِيرْ، وَأشْهَدُ أنَّ مُحَمَّدًا رسُوْلُ اللهِّۢ الْبشَيرْ وَالنذَّيرْ، وَالصَّلاَةُ وَالسَّلامَ عَلَيْه والِۢه وَأصَحَابِه إلِۢى يوَمِ المْصَيرْ، أمَّا بَعْدُ أعَوْذُ بِاللهِّۢ مِنَ الشَّيْطَانِ الرجَّيْمِ، بِسْمِ اللهِ الرحَّمَنِ ال ِّرحِيمِ. الْحَمْدُ للهِ ر ِّبَ الْعَالمَيْنَ، الصَّلاَةُ وَالسَّلامَ عَلَيْكَ يَا سَ ِّيدِيْ يَا رسُوْلُ اللهِّۢ خُذْ بِيدَيْ قَلُّتِحِيلَ ِتيٓ ادَرِكْ ِنيْ، اللَّهُمَّ إنَّا نَعُوذُ بِكِمنَ وَالقَسْوَ ِة وَالغَفلَة وَالعَيلَة وَالذِّلَّة والمسَكَنةَ، اللَّهُمَّ الْطُفْ بِناَ فِي تيَسِيرِ كُ ِّل عَسِيرٍ فَإِنَّ تَيْسِيرَ كُ ِّل عَسِيرٍ عَلَيْكَ يَسِيرٌ، وَنَسْألُكَ الْيُسْرَ وَالمْعُۢافَاةَ فِي الدُّنيْا وَالآخِرَةِ رَبنَّاَ لاَ تزُغْ قُلُوبنَاَ بَعْدَ إذْ هَدَيتْنَاَ وَهَبْ لَناَ مِنْ لَدُنْكَ رحْمَةً إنَّكَ انَتْ الْوَهَّابُ، رَبنَّاَ اشْرحْ لَناَ صُدُوْرنَا وَيَ ِّسرْ لَنَآ أمُوْرنَا وَاحْلُلْ عُقْدَةً مِنْ ألْسِنتَناَيفَقَهُوٓاْ أقْوْالَناَ اللَّهُمَّ إنَّا نَسْألُكَ خَوفَ العَ ِالمِينَ بِكَ وَ ِعلْمَ الخَا ِئفِينَمنكَ وَيقَينَ المتُوَ ِّكَليِنَ عَلَـيْكَ وَرجَى الراَّغِبِيْنَ فِيْكَ وَزُهْدَ الطَّالبِيْنَ إلَيْكَ وَوَرعَ المْحُبِّيْنَ لَكَ وَتَقْوَى المْتُشَ ِّوقِيْنَ إلَيْكَ، وَالْحَمْدُ للهِ ر ِّبَ الْعَالمَيْنَ',
        latin:'Alhamdu lillaahil aliyyil kabir, as sami il ba-shiir, asy-hadu al laa ilaaha  illallaahul alimul khabir, wa asy-hadu anna muhammadar rasuulullas aahit ba-syiru wan nadzir, wash shalaatu was salaamu alaihi wa aalihiws ashhaabihi ilaa yaumil ma-shiir, ammaa ba du .A uu dzu billaahi minasy syai-thaanir rajim Bismillaahir rahmaanir rahiim Alhamdu lillaahi rabbil aalamiin Ash shalaatu adalah salaamu alaika yaa savyıdi yaa rasuululallah, khudz bi yadi gallat hillati adrikniı Allaahumma innaa na uu dzu bika minal qaswati wal ghaflatiwal ailati wadz dzillati wal maskanatı Allaahummal thut binaati taisin kulli asirin fa inna taisirakulli asitin alaika yasiirun,wa nas-alukal yusra wal mu aalaata tid dun-yaa wal aa-khirah. Rabbanaa laa tuzigh quluubanaa ba da idz hadaitanaa wa hab lanaa mil ladungka rahmah, innaka antal wahhaab. Rabbanasy-rah lanaa shuduuranaa wa yassir lanaa umuuranaa wahlul uqdaatam min alsinatinaa, yafqahuu aqwaalanaa Allaahumma innaa nas-aluka khaufal aalamiina bika wa lmal khaa-ifina mingka wa yaqinal mutawakkilina alaika wa rajar raa- ghibina fika wa zuhdath thaaibina ilaika wa wara al muhibbina laka wa taqwal muta-syawwiqina ilaika Rabbanaa aatinaa fid dun-yaa hasanah, wa fil aa-khirati hasanah, wa qinaa a -dzaaban naar Walhamdu lillaahi rabbil aalamiin.',
        arti:'Artinya: "Segala puji bagi Allah yang Maha Tinggi lagi Maha Besar, Maha Mendengar lagi Maha Melihat. Aku bersaksi bahwa tidak ada Tuhan selain Allah, yang Maha Mengetahui lagi Maha Mengenal. Dan aku bersaksi bahwa Nabi Muhammad adalah utusan Allah, pemberi kabar gembira serta peringatan. Shalawat dan salam semoga tercurah kepadanya, keluarga dan para sahabatnya sampai hari kembali (kepada Allah). Adapun sesudah itu.Aku berlindung kepada Allah dari segala dewaaan syctan yang engan nama Allah yang Maha Pengasıh lag terkutuk. Aku Maha Penyayang Segala puji bagi Allah Allah semesta alam Rahmat dan salam semoga tetap tercurah kepadamu wahai junjunganku wahai perpisahan Allah, ambillah dengan tanganku, sungguh sedıkit upayaku, tepukanlah aku Ya Allah, sesungguhnya kamı berlindung kepada-Mu dari kerasnya hati, lalai, banyak tanggungan, kehinaan dan kemiskinan. Ya Allah. kasihanılah kamı dalam membantu setiap perkara yang sulit, karena sesungguhnya setiap perkara yang sulit itu bagi-Mu sangat mudah dan kami mohon kenyamanan serta dunia dan akhirat Waha Tuhan kami, janganlah Engkau sesatkan hati kami setelah Engk au memberi petunjuk kepada kami dan berilah kamı rahmat dari sisi Engkau, sesungguhnya Engkau adalah Maha Pemberi. Wahai Tuhan kami, lapangkanlah dada kami mudahkanlah kondisi kami, bukalah rubah penglihatan, kami bisa agar mereka memahami kami. Ya Allah, sesungguhnya kami memohon kepada-Mu kiat orang orang yang mengenal-Mu, menghormati orang yang takut kepada-Mu, menghormati orang yang bertawakal kepada-Mu. orang orang yang mencintal-Mu, kezuhudan orang orang yang mencari-Mu, kewara an (menjaga diri) orang-orang yang cinta kepada Mu dan orang-orang kejam untuk orang-orang di Mu ngat kami, berilah kami di dunia, dan membantu diakhirat , dan peliharalah kami dari siksa neraka Segala puji bagi Allah Tuhan semesta alam ".',
    },
    {
        user:'doa26',
        subject:'doa acara Isra mi raj,nuzulul quran,khutbah jum at,dll',
        isi:'الْحَمْدُ لِلهِ الَّذِيْ وَفَّقَناَ لاِدَاءِ الْجُمُعِ وَالْجَمَاعَاتِ، وَهَدَانَٓا إلِۢى سَبِيْلِ اكْتِسَابِ اكَمَلِ السَّعَادَاتِ أشْهَدُ أنَ لآ إلِۢهَ إلِاَّ اللهُّۢ ربُّ الاْراَضِيْنَ وَالسَّمۢوَاتِ، وَأشَهَدُ أنَّ مُحَمَّدًا رسُوْلُ اللهِّۢ المْؤُيدَّ بِأفْضَلِ الآْيَاتِ وَالمْعُجزِاَتِ يَا ر ِّبَ صَ ِّل وَسَ ِّلمْ عَلۢى سَ ِّيدِنَا مُحَمَّدٍ وَالِۢه وَصَحْبِه مَا تَعَاقَبَ الاْوْقَا ِت والسَّاعَا ِت امَّا بَعْدُ فيَاِعباَدَ اللهِّۢ اوُ ِصيْكُمْ وَنفْ ِسيْ بِتقْوۢى اللهِّۢ وَحَافِظوُا عَلۢى طاَعَتِه وَحُظوُرِ الْجُمُعِ وَالْجَمَاعَاتِ أعَوْذُ بِاللهِّۢ مِنَ الشَّيْطَانِ الرجَّيمِ، بِسْمِ اللهِ الرحَّمَنِ ال ِّرحِيمِ. حَمْدَ الشَّاكِرِيْنَ حَمْدَ الناَّعِمِيْنَ، حَمْدًا يوُافِى نِعَمَهُ وَيُكَافِى مَزِيدَهُ، يَارَبنَّاَ لَكَ الْحَمْدُ كَمَا يَنبْغَى لِجَلاَلِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ  ',
        latin:'',
    }
]